[package]
name = "fern"
version = "0.1.0"
authors = ["Mads Horn <madshorn@operamail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.10.0"
rand = "0.6.5"
